Repository calm1205/golf_academy, pull requests merged in 2023-04, with the labels that each got.

#4 npm run startのスクリプト変更
  package.json
Labels: Doing

#16 Feature/copyright
  .DS_Store
  .gitignore
  src/.DS_Store
  src/components/.DS_Store
  src/components/footer/copyright.php
  src/components/footer/footer.php
  src/dist/output.css
  src/index.php
Labels: Done

#17 Feature/footer
  src/components/footer/copyright.php
  src/components/footer/footer.php
  src/dist/output.css
  src/index.php
Labels: Done

#18 タイトルの実装
  src/components/content/content.php
  src/components/content/title/line.php
  src/components/content/title/title.php
  src/dist/output.css
  src/global.css
  tailwind.config.js
Labels: Done

#25 header
  src/asset/afterGolfStudio.png
  src/components/header/header.php
  src/components/header/menu.php
  src/components/ui_parts/logo.svg
Labels: Done

#23 Feature/button
  src/components/content/button.php
  src/components/content/content.php
  src/dist/output.css
Labels: Review back

#30 Feature/baloon
  src/components/content/baloon/baloon.php
  src/components/content/content.php
  src/dist/output.css
  src/index.php
  tailwind.config.js
Labels: Done

#29 Feature/news
  src/components/content/news/news.php
  src/dist/output.css
Labels: Done

#28 Feature/guidance
  src/components/content/content.php
  src/components/content/guidance/guidance.php
Labels: Done

#34 Feature/button layout
  src/asset/guidance/guidance.png
  src/components/content/balloon/balloon.php
  src/components/content/content.php
  src/components/content/guidance/guidance.php
  src/components/content/guidance/guidanceTable.php
  src/components/content/handFree/handFree.php
  src/components/content/introduction/introduction.php
  src/components/content/lessonStaff/lessonStaff.php
  src/components/ui_parts/button/button.php
Labels: Review back

#35 Feature/news layout
  src/components/content/balloon/balloon.php
  src/components/content/chiropractor/chiropractor.php
  src/components/content/content.php
  src/components/content/handFree/handFree.php
  src/components/content/junior/junior.php
  src/components/content/lessonStaff/lessonStaff.php
  src/components/ui_parts/section/section.php
Labels: Done

#46 Rental shoes
  src/asset/rental/club.png
  src/asset/rental/glove.png
  src/asset/rental/shoes.svg
  src/components/rental/club/club.php
  src/components/rental/glove/glove.php
  src/components/rental/header/header.php
  src/components/rental/rental.php
  src/components/rental/shoes/shoes.php
  src/index.php
Labels: Done

#47 Feature/rental club
  src/components/rental/club/club.php
  src/components/rental/club/clubTable.php
  src/components/rental/rental.php
Labels: Doing

#54 [施設案内] ヘッダー
  src/asset/facility/facility.png
  src/components/facility/facility.php
  src/components/header/menu.php
  src/components/rental/header/header.php
  src/index.php
Labels: Done

#56 [施設概要] 練習設備トラックマン
  src/asset/facility/facility.png
  src/asset/facility/trackman/trackman1.png
  src/asset/facility/trackman/trackman2.png
  src/components/facility/facility.php
  src/components/facility/trackman/trackman.php
  src/components/header/menu.php
  src/components/rental/header/header.php
  src/index.php
Labels: Doing

#55 施設案内ページ
  src/asset/facility/facility.png
  src/asset/facility/trackman/trackman1.png
  src/asset/facility/trackman/trackman2.png
  src/components/content/content.php
  src/components/facility/chiropractor/chiropractor.php
  src/components/facility/facility.php
  src/components/facility/overview/overview.php
  src/components/facility/trackman/trackman.php
  src/components/header/menu.php
  src/components/rental/header/header.php
  src/components/ui_parts/access/map.php
  src/components/ui_parts/guidance/guidance.php
  src/components/ui_parts/guidance/guidanceTable.php
  src/index.php
Labels: Done

#62 [共通][リファクタリング]
  src/components/content/content.php
  src/components/features/facility/chiropractor/chiropractor.php
  src/components/features/facility/facility.php
  src/components/features/facility/overview/overview.php
  src/components/features/facility/trackman/trackman.php
  src/components/features/rental/club/club.php
  src/components/features/rental/club/clubTable.php
  src/components/features/rental/glove/glove.php
  src/components/features/rental/header/header.php
  src/components/features/rental/rental.php
  src/components/features/rental/shoes/shoes.php
  src/components/features/top/chiropractor/chiropractor.php
  src/components/features/top/handFree/handFree.php
  src/components/features/top/header/header.php
  src/components/features/top/introduction/introduction.php
  src/components/features/top/junior/junior.php
  src/components/features/top/lessonStaff/lessonStaff.php
  src/components/features/top/news/news.php
  src/components/features/top/top.php
  src/components/rental/rental.php
  src/components/ui_parts/balloon/balloon.php
  src/components/ui_parts/footer/copyright.php
  src/components/ui_parts/footer/footer.php
  src/components/ui_parts/header/header.php
  src/components/ui_parts/header/menu.php
  src/components/ui_parts/section/section.php
  src/components/ui_parts/title/line.php
  src/components/ui_parts/title/title.php
  src/index.php
Labels: Done

#71 [レスポンシブ対応] メニューの開閉制御
  src/components/ui_parts/header/header.php
  src/components/ui_parts/header/menu.phone.php
  src/components/ui_parts/header/menu/close.svg
  src/components/ui_parts/header/menu/menu.phone.js
  src/components/ui_parts/header/menu/menu.phone.php
  src/components/ui_parts/header/menu/menu.php
Labels: Done
