Repository calm1205/golf_academy, pull requests merged in 2023-07, with the labels that each got.

#84 Feature/new rental
  src/asset/chiropractor/newChiropractor.png
  src/asset/handFree/newClub.png
  src/asset/introduction/newLesson.png
  src/asset/introduction/newTrackman.png
  src/asset/junior/newJunior.png
  src/components/features/rental/club/club.php
  src/components/features/rental/glove/glove.php
  src/components/features/rental/rental.php
  src/components/features/rental/shoes/shoes.php
  src/components/features/top/facilityIntro/facilityInfo.php
  src/components/features/top/introduction/introduction.php
  src/components/features/top/lessonStaff/lessonStaff.php
  src/components/features/top/top.php
Labels: Done

#81 Feature/new introduction
  src/components/features/top/facilityIntro/facilityInfo.php
  src/components/features/top/introduction/introduction.php
Labels: Done

#82 Feature/new facility
  src/asset/facility/trackman/newTrackman2.png
  src/components/features/facility/chiropractor/chiropractor.php
  src/components/features/facility/facility.php
  src/components/features/facility/trackman/trackman.php
  src/components/features/top/facilityIntro/facilityInfo.php
  src/components/features/top/introduction/introduction.php
Labels: Done

#90 料金プランページ実装
  src/asset/prices/prices.png
  src/components/features/prices/prices.php
  src/components/ui_parts/header/menu/menu.php
  src/index.php
Labels: Done

#91 Section内のLogo画像配置
  src/asset/title/logo.svg
  src/components/features/top/facilityIntro/facilityInfo.php
  src/components/features/top/lessonStaff/lessonStaff.php
  src/components/ui_parts/title/title.php
Labels: Done

#92 料金プランのセクションをループ
  src/components/features/prices/notes/notes.php
  src/components/features/prices/prices.php
  src/components/features/prices/section/section.php
Labels: Done

#93 画像付きカードの流用
  src/components/features/facility/chiropractor/chiropractor.php
  src/components/features/facility/facility.php
  src/components/features/facility/trackman/trackman.php
  src/components/features/rental/card/card.php
  src/components/features/rental/club/club.php
  src/components/features/rental/rental.php
  src/components/features/top/chiropractor/chiropractor.php
  src/components/features/top/facilityIntro/facilityInfo.php
  src/components/features/top/handFree/handFree.php
  src/components/features/top/introduction/introduction.php
  src/components/features/top/junior/junior.php
  src/components/features/top/lessonStaff/lessonStaff.php
  src/components/ui_parts/card/card.php
  src/components/ui_parts/card/cardWithButton.php
  src/components/ui_parts/card/imageCardLeft.php
  src/components/ui_parts/card/imageCardRight.php
  src/components/ui_parts/section/section.php
  src/components/ui_parts/section/title/title.php
  src/components/ui_parts/title/line.php
Labels: Done

#94 Feature/main fix
  src/components/features/facility/chiropractor/chiropractor.php
  src/components/features/facility/trackman/trackman.php
  src/components/features/prices/prices.php
  src/components/features/prices/section/section.php
  src/components/features/top/introduction/introduction.php
  src/components/ui_parts/card/card.php
Labels: Done

#95 Feature/new responsive top
  src/components/features/top/facilityIntro/facilityInfo.php
  src/components/features/top/introduction/introduction.php
  src/components/features/top/lessonStaff/lessonStaff.php
  src/components/ui_parts/card/phone.card.php
  src/components/ui_parts/guidance/guidance.php
  src/components/ui_parts/guidance/guidanceTable.php
Labels: Done

#96 Feature/responsive facility
  src/components/features/facility/chiropractor/chiropractor.php
  src/components/features/facility/facility.php
  src/components/features/facility/trackman/trackman.php
  src/components/features/prices/prices.php
  src/components/features/top/facilityIntro/facilityInfo.php
  src/components/features/top/introduction/introduction.php
  src/components/ui_parts/button/button.php
  src/components/ui_parts/card/card.phone.php
  src/components/ui_parts/header/headerImage/headerImage.php
Labels: Done

#99 Feature/new responsive rental
  src/components/features/rental/club/club.php
  src/components/features/rental/club/clubTable.php
  src/components/features/rental/header/header.php
  src/components/features/rental/rental.php
  src/components/ui_parts/card/card.phone.php
Labels: Doing

#103 Feature/images
  src/asset/header/logo.svg
  src/asset/lesson/staff_responsive.png
  src/asset/title/logo.svg
  src/asset/top/backgroundLogo.png
  src/asset/top/title.png
  src/asset/top/title_responsive.png
  src/asset/top/top.png
  src/asset/top/topResponsive.png
  src/asset/top/top_responsive.png
  src/components/features/top/header/header.php
  src/components/features/top/lessonStaff/lessonStaff.php
  src/components/features/top/top.php
  src/components/ui_parts/header/header.php
Labels: Done

#104 Feature/coaches
  src/asset/coaches/Group 10.png
  src/asset/coaches/Group 9.png
  src/asset/coaches/coach1.png
  src/asset/coaches/coach2.png
  src/asset/coaches/twoSpuares.png
  src/asset/coaches/twoSquaresReverse.png
  src/components/features/coaches/coaches.php
  src/components/features/top/header/header.php
  src/components/features/top/top.php
  src/components/ui_parts/header/menu/menu.php
  src/index.php
Labels: Request review

#105 Feature/responsive coaches
  src/asset/coaches/coach1_responsive.png
  src/asset/coaches/coach2_responsive.png
  src/components/features/coaches/coaches.php
  src/components/ui_parts/header/menu/menu.phone.php
Labels: Request review
